ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  secret: $JWT_SECRET
couch:
    username: $CDB_USERNAME
    password: $CDB_PASSWORD